// import AuthContext from '@/contexts/AuthContext'
import AuthContext from '@/lib/contexts/AuthContext'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/app/components/Header'
import Footer from '@/app/components/Footer'
import './globals.css'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import { getSession } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)

  console.log('layout session: ', session)
  return (
    <html lang="ko">
      <AuthContext>
        <body className={inter.className}>
          <Header session={session} />
          {children}
          <Footer />
        </body>
      </AuthContext>
    </html>
  )
}
